import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/shared/ThemeProvider";

export const metadata: Metadata = {
  title: "TutorSpace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-slate-950 text-foreground overflow-x-hidden min-h-screen">
        <ThemeProvider>
          {/* Universal Glassmorphism Background */}
          <div className="fixed inset-0 -z-10 bg-slate-950 pointer-events-none">
            <div className="absolute -top-40 -left-20 w-[500px] h-[500px] bg-purple-500/20 rounded-full mix-blend-screen filter blur-[120px]" />
            <div className="absolute top-1/4 -right-20 w-[600px] h-[600px] bg-blue-500/10 rounded-full mix-blend-screen filter blur-[120px]" />
            <div className="absolute -bottom-40 left-1/2 -translate-x-1/2 w-[800px] h-[500px] bg-indigo-500/15 rounded-full mix-blend-screen filter blur-[150px]" />
          </div>

          <div className="relative">
            {children}
            <Toaster richColors position="top-right" /> 
          </div>
        </ThemeProvider>

      </body>
    </html>
  );
}
