"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Sparkles, ChevronDown, ChevronUp, Trash2 } from "lucide-react"
import { deletePracticeSet } from "@/services/practice"
import QuizPlayer from "./QuizPlayer"
import type { PracticeSet } from "./types"

/**
 * The student's practice page, in two groups:
 *
 * - My quizzes: generated by this student from a course PDF. Private to them,
 *   and labelled as not reviewed by the tutor.
 * - From your tutors: sets a tutor generated, read and published for the
 *   whole course.
 *
 * Nothing here is graded or saved as a result.
 */
export default function StudentPracticePage({ sets }: { sets: PracticeSet[] }) {
  const router = useRouter()
  const mine = sets.filter((s) => s.student_id)
  const fromTutor = sets.filter((s) => !s.student_id)
  const [openId, setOpenId] = useState<string | null>(mine[0]?.id ?? fromTutor[0]?.id ?? null)
  const [deletingId, setDeletingId] = useState<string | null>(null)

  const handleDelete = async (id: string) => {
    try {
      setDeletingId(id)
      const res = await deletePracticeSet(id)
      if (res?.status === "success") {
        toast.success("Quiz deleted")
        router.refresh()
      } else {
        toast.error(res?.message || "Could not delete the quiz")
      }
    } catch {
      toast.error("Something went wrong")
    } finally {
      setDeletingId(null)
    }
  }

  const renderSet = (set: PracticeSet, own: boolean) => {
    const isOpen = openId === set.id
    return (
      <Card key={set.id}>
        <CardContent className="py-4 space-y-4">
          <div className="flex items-center gap-3 flex-wrap">
            <div className="min-w-0 flex-1">
              <div className="font-medium truncate">{set.title}</div>
              <div className="flex items-center gap-2 mt-1 flex-wrap">
                <Badge variant="outline">{set.course?.name ?? "Course"}</Badge>
                {own ? (
                  <Badge variant="secondary">AI-generated, not reviewed by your tutor</Badge>
                ) : (
                  <Badge>Reviewed by your tutor</Badge>
                )}
                <span className="text-xs text-muted-foreground">
                  {set.questions?.length ?? 0} questions
                  {set.material?.title ? ` · from “${set.material.title}”` : ""}
                </span>
              </div>
            </div>

            <Button
              size="sm"
              variant="outline"
              className="gap-1"
              onClick={() => setOpenId(isOpen ? null : set.id)}
            >
              {isOpen ? (
                <>
                  <ChevronUp className="h-4 w-4" />
                  Close
                </>
              ) : (
                <>
                  <ChevronDown className="h-4 w-4" />
                  Take quiz
                </>
              )}
            </Button>
            {own && (
              <Button
                size="sm"
                variant="ghost"
                aria-label="Delete quiz"
                className="text-destructive hover:text-destructive"
                disabled={deletingId === set.id}
                onClick={() => handleDelete(set.id)}
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            )}
          </div>

          {isOpen && (
            <div className="pt-3 border-t">
              <QuizPlayer questions={set.questions ?? []} />
            </div>
          )}
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="max-w-7xl mx-auto py-10 px-4 space-y-8">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Sparkles className="h-6 w-6" />
          Practice Quizzes
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Generate a quiz from any PDF in{" "}
          <Link href="/dashboard/materials" className="underline">
            Course Materials
          </Link>
          . Quizzes are for revision only and are not graded.
        </p>
      </div>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold">My quizzes</h2>
        {mine.length === 0 ? (
          <Card>
            <CardContent className="py-10 text-center text-muted-foreground">
              You haven&apos;t generated a quiz yet. Open Course Materials and
              choose <span className="font-medium">Practice quiz</span> on a PDF.
            </CardContent>
          </Card>
        ) : (
          mine.map((s) => renderSet(s, true))
        )}
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold">From your tutors</h2>
        {fromTutor.length === 0 ? (
          <Card>
            <CardContent className="py-10 text-center text-muted-foreground">
              None yet. Sets appear here when a tutor publishes one for a
              course you have booked.
            </CardContent>
          </Card>
        ) : (
          fromTutor.map((s) => renderSet(s, false))
        )}
      </section>
    </div>
  )
}
